# Generated by Django 4.0.3 on 2022-04-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('pet_category', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=64)),
                ('img', models.CharField(max_length=128)),
                ('user', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
