# Generated by Django 4.0.3 on 2022-04-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0002_rename_author_post_authorid_post_authorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.CharField(max_length=256),
        ),
    ]
