# Generated by Django 4.0.3 on 2022-04-16 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts_api', '0009_remove_post_users_who_liked_post_post_users_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='users_liked_by',
            field=models.ManyToManyField(blank=True, related_name='users_liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
